name: deploy
env:
  BRANCH: main

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      
      - name: add target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install trunk
        uses: baptiste0928/cargo-install@v1
        with:
          crate: trunk

      - name: install cargo-script
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-script

      - run: mkdir -p .output

      - run: trunk build --release --public-url "$REPOSITORY_NAME/"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/dist
          publish_branch: pages
          destination_dir: ./
          enable_jekyll: false
